[package]
name = "cam_core_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cam_core_lib = { path = "../../engine" }

clap = { version = "4.0.0", features = ["derive", "wrap_help"] }
ariadne = "0.1.5"
colored = "2.0.0"
